spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/projectTest
    username: sa
    password: 1024
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace